# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.java.home=/home/libreh/.sdkman/candidates/java/21.0.12+1.1-tem

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
loader_version=0.16.9
loom_version=1.9.2

# Mod Properties
mod_version=0.2.2
maven_group=me.libreh
archives_base_name=worldreset
is_stable=true

# Dependencies
fabric_version=0.116.17+1.21.1
permissions_api_version=0.3.3
arcade_version=0.4.1-beta.28-libreh.1+1.21.1
predicate_api_version=0.5.2+1.21
